### 1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [81]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as metrics

In [119]:
# se importa el dataset y se convierte en dataframe para filtrarlo
digits = load_digits() 
df = pd.DataFrame(data= np.c_[digits['data'], digits['target']])
df_fil = df[(df[64]==1) | (df[64]==9)]
dig_fil = np.array(df_fil)

# se separan los datos y se entrena el modelo con ellos
X = dig_fil[:,:-1]
y = dig_fil[:,64]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
logisticRegr = LogisticRegression(max_iter=10000)
logisticRegr.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [120]:
# predicción y análisis de resultados
y_pred = logisticRegr.predict(X_test)
print("score de predicción:", logisticRegr.score(X_test, y_test))
print("Matriz de confusión:\n", metrics.confusion_matrix(y_test, y_pred))

score de predicción: 0.9863013698630136
Matriz de confusión:
 [[37  0]
 [ 1 35]]


¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?
Si, se mejora el acierto, puede ser porque al haber menos clases, sea más fácil encontrar patrones o porque estas clases son las más fáciles de reconocer. Habría que repetir el análisis para otros números a ver si en esos casos el porcentaje aumenta también.

In [99]:
# se importa el dataset y se convierte en dataframe para filtrarlo
df_fil28 = df[(df[64]==2) | (df[64]==8)]
dig_fil28 = np.array(df_fil28)

# se separan los datos y se entrena el modelo con ellos
X28 = np.array(dig_fil28[:,:-1])
y28 = np.array(dig_fil28[:,64])
X28_train, X28_test, y28_train,y28_test = train_test_split(X28, y28, test_size=0.20, random_state=42)
logisticRegr28 = LogisticRegression(max_iter=10000)
logisticRegr28.fit(X28_train, y28_train)

# predicción y análisis de resultados
y28_pred = logisticRegr28.predict(X28_test)
print("score de predicción:", logisticRegr28.score(X28_test, y28_test))
print("Matriz de confusión:\n", metrics.confusion_matrix(y28_test, y28_pred))

score de predicción: 0.9859154929577465
Matriz de confusión:
 [[35  0]
 [ 1 35]]


Al hacer la prueba con dos números distintos, el porcentaje sigue siendo igual de alto, por lo que no se puede atribuir a que los número s1 y 9 tengan patrones más reconocibles.

In [98]:
# se importa el dataset y se convierte en dataframe para filtrarlo
df_fil3 = df[(df[64]==2) | (df[64]==8)| (df[64]==7)]
dig_fil3 = np.array(df_fil3)

# se separan los datos y se entrena el modelo con ellos
X3 = np.array(dig_fil3[:,:-1])
y3 = np.array(dig_fil3[:,64])
X3_train, X3_test, y3_train,y3_test = train_test_split(X3, y3, test_size=0.20, random_state=42)
logisticRegr3 = LogisticRegression(max_iter=10000)
logisticRegr3.fit(X3_train, y3_train)

# predicción y análisis de resultados
y3_pred = logisticRegr3.predict(X3_test)
print("score de predicción:", logisticRegr3.score(X3_test, y3_test))
print("Matriz de confusión:\n", metrics.confusion_matrix(y3_test, y3_pred))

#predicción total
y3_pred_tot = logisticRegr3.predict(X3)
print("score de predicción:", logisticRegr3.score(X3, y3))
print("Matriz de confusión:\n", metrics.confusion_matrix(y3, y3_pred_tot))



score de predicción: 1.0
Matriz de confusión:
 [[39  0  0]
 [ 0 32  0]
 [ 0  0 35]]
score de predicción: 1.0
Matriz de confusión:
 [[177   0   0]
 [  0 179   0]
 [  0   0 174]]


Al hacer la prueba con tres clases, el resultado es aun mejor que con dos, por lo que no se puede concluir que la mejora se deba a que haya menos clases.

In [114]:
# se separan los datos y se entrena el modelo con ellos
X10 = digits.data
y10 = digits.target
X10_train, X10_test, y10_train,y10_test = train_test_split(X10, y10, test_size=0.20, random_state=42)
logisticRegr10 = LogisticRegression(max_iter=10000)
logisticRegr10.fit(X10_train, y10_train)

# predicción y análisis de resultados
y10_pred = logisticRegr10.predict(X10_test)
print("score de predicción:", logisticRegr10.score(X10_test, y10_test))
print("Matriz de confusión:\n", metrics.confusion_matrix(y10_test, y10_pred))

#predicción total
y10_pred_tot = logisticRegr10.predict(X10)
print("score de predicción:", logisticRegr10.score(X10, y10))
print("Matriz de confusión:\n", metrics.confusion_matrix(y10, y10_pred_tot))

# predicción total mejorada
logisticRegr10bis = LogisticRegression(max_iter=10000, tol=1e-10, C=0.1, class_weight='balanced', solver='lbfgs', n_jobs=-1)
logisticRegr10bis.fit(X10_train, y10_train)
y10bis_pred_tot = logisticRegr10bis.predict(X10)
print("score de predicción:", logisticRegr10bis.score(X10, y10))
print("Matriz de confusión:\n", metrics.confusion_matrix(y10, y10bis_pred_tot))


score de predicción: 0.9722222222222222
Matriz de confusión:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  1  0  0 44  1  0  0  1]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  1  0 33  0  0]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  1 38]]
score de predicción: 0.9944351697273233
Matriz de confusión:
 [[178   0   0   0   0   0   0   0   0   0]
 [  0 182   0   0   0   0   0   0   0   0]
 [  0   0 177   0   0   0   0   0   0   0]
 [  0   0   0 182   0   1   0   0   0   0]
 [  0   1   0   0 180   0   0   0   0   0]
 [  0   0   1   0   0 179   1   0   0   1]
 [  0   0   0   0   0   1 180   0   0   0]
 [  0   0   0   0   0   1   0 178   0   0]
 [  0   0   0   0   0   1   0   0 173   0]
 [  0   0   0   1   0   0   0   0   1 178]]
score de predicción: 0.9944351697273233
Matriz de confusión:
 [[178   0   0   0   0   0   0   0   0   0]
 [  0 182

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

se han modificado varios argumentos de la función sin que ello haya significado una mejora en el resultado del modelo de regressión.