# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np 

my_array = np.arange(10)
print (my_array[-1:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [5]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [7]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [17]:
array20= np.arange(1,21)
matrix45 = np.reshape(array20, (5,4))
matrix45T= np.transpose(matrix45)
print(matrix45)
print("------------")
print(matrix45T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
------------
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [19]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x_out = []
for i in range(len(x)):
    if x[i] == "Loro":
        x_out.append(x[i])
x_out

['Loro', 'Loro']

In [20]:
x_out2 = np.where(x == "Loro", "Loro", "")
x_out2

array(['Loro', '', '', 'Loro', ''], dtype='<U4')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [25]:
array20_2= np.arange(20)
array2x5x2 = np.reshape(array20_2, (2,2,5))
array2x5x2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [41]:
array20= np.arange(1,21)[::-1]
array2054 = np.reshape(array20, (4,5))
array2054

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
from sys import getsizeof

array0 = np.zeros(10)
print(array0)

print(getsizeof(array0),"B")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
184 B


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [46]:
array1049 = np.arange(10,50)
array1049_inv = array1049[::-1]
array1049_inv

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [37]:
t = np.array([1,2,0,0,4,0])
index_ar = np.nonzero(t != 0)
print(index_ar)

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [5]:
matrix10x10 = np.random.randint(0,9, size = (10,10))
print(matrix10x10)
print(np.max(matrix10x10))
print(np.min(matrix10x10))

[[6 2 3 0 2 5 3 8 3 2]
 [7 1 6 4 3 7 2 7 5 6]
 [1 4 0 5 0 3 2 7 1 2]
 [5 1 3 0 6 3 1 5 2 0]
 [6 0 8 8 2 6 2 7 6 6]
 [8 5 7 4 4 3 3 3 8 8]
 [2 1 7 8 7 8 4 0 6 7]
 [5 8 8 5 1 3 3 7 4 8]
 [7 2 3 2 7 8 1 6 8 4]
 [6 4 8 5 2 6 5 6 7 7]]
8
0


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [8]:
arrayx30 = np.random.randint(0,9, size = (30))
print(arrayx30)
print(np.average(arrayx30))

[6 6 3 0 0 7 4 4 8 8 4 8 4 7 6 1 4 8 2 0 2 2 8 2 8 6 6 6 3 6]
4.633333333333334


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [17]:
square10x10 = np.zeros((10,10))
square10x10[0] += 1
square10x10[9] += 1
square10x10[:,0] += 1
square10x10[:,9] += 1
square10x10[0][0] -= 1
square10x10[0][9] -= 1
square10x10[9][0] -= 1
square10x10[9][9] -= 1
print(square10x10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [41]:
matri8x8 = np.zeros((8,8), int)
for i in range(8):
    for j in range (8):
        if i%2 == 1:
            if j%2 == 0:
                matri8x8[i][j] = 1
        else:
            if j%2 == 1:
                matri8x8[i][j] = 1
matri8x8

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [44]:
seed = np.array([[0,1],[1,0]])
mat8x8_tile = np.tile (seed, (4,4))
mat8x8_tile 

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [52]:
randmat5x5 = np.random.randint(0,9, (5,5))
print(randmat5x5)

avg = np.mean(randmat5x5)
print(avg)

std = np.std(randmat5x5)
print (std)

norm = (randmat5x5 -avg)/std
print(norm)

[[4 7 7 3 5]
 [5 0 7 8 5]
 [5 0 2 4 6]
 [1 5 4 1 6]
 [5 1 6 8 2]]
4.28
2.3919866220361685
[[-0.11705751  1.13713011  1.13713011 -0.53512005  0.30100503]
 [ 0.30100503 -1.78930767  1.13713011  1.55519264  0.30100503]
 [ 0.30100503 -1.78930767 -0.95318259 -0.11705751  0.71906757]
 [-1.37124513  0.30100503 -0.11705751 -1.37124513  0.71906757]
 [ 0.30100503 -1.37124513  0.71906757  1.55519264 -0.95318259]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [58]:
array10 = np.arange(0,11)
array10bis = np.where (array10 >= 3,np.where (array10 <= 8, -1, array10), array10)
array10bis
array10bis2 = np.where (array10 >= 3,np.where (array10 <= 8, -1*array10, array10), array10)
array10bis2

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.