En el apartado "Loading Data" de esta URL:

https://www.datacamp.com/community/tutorials/svm-classification-scikit-learn-python

Se explica cómo se cargan una serie de datos: 

1. Utiliza esa misma forma para cargar los datos.
2. Limpia los datos si es necesario
3. Utiliza los métodos de clasificación vistos hasta ahora para clasificar el target de los datos, ¿cuál da mejores resultados? 

El modelo que mejor predice los datos a priori es el SVC

4. Intenta superarte en el score cambiando las features de los algoritmos.

Subiendo el parámetro C a 100 se obtiene una mejora de 2 décimas en el score.

In [2]:
#Import scikit-learn dataset library
from sklearn import datasets

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb

#se carga el dataset y se asignan los valores del dataset a las variables con las que se va a trabajar con el modelo
cancer = datasets.load_breast_cancer()
X = cancer.data
y = cancer.target

In [3]:
# Análisis de rendimiento del modelo de regresión logística
model_LogReg = linear_model.LogisticRegression(max_iter=5000, tol=1e-6) # Máximo número de operaciones =500 -> comprobar el éxito de entrenamiento con score
model_LogReg.fit(X,y)
predictions_LogReg = model_LogReg.predict(X)
print(model_LogReg.score(X,y))
print(confusion_matrix(y, predictions_LogReg))

0.9578207381370826
[[197  15]
 [  9 348]]


In [4]:
# Análisis de rendimiento del modelo Knn
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=20)
model_knn.fit(X, y)
predictions_knn = model_knn.predict(X)
print(model_knn.score(X,y))
print(confusion_matrix(y, predictions_knn))

0.9367311072056239
[[186  26]
 [ 10 347]]


In [5]:
# Análisis de rendimiento del modelo support vector machine - linear SVC
from sklearn import svm

model_linSVC = svm.LinearSVC(max_iter=1000000, C=1)
model_linSVC.fit(X, y)
predictions_linSVC = model_linSVC.predict(X)
print(model_linSVC.score(X,y))
print(confusion_matrix(y, predictions_linSVC))


0.9666080843585237
[[207   5]
 [ 14 343]]
C:\Users\barke\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\svm\_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [8]:
# Análisis de rendimiento del modelo support vector machine - linear SVC
from sklearn import svm

model_SVC = svm.SVC(kernel='linear', max_iter=10000000, C=1)
model_SVC.fit(X, y)
predictions_SVC = model_SVC.predict(X)
print(model_SVC.score(X,y))
print(confusion_matrix(y, predictions_SVC))

0.9666080843585237
[[201  11]
 [  8 349]]


In [10]:
# Análisis de rendimiento del modelo support vector machine - poly SVC
from sklearn import svm

model_SVC = svm.SVC(kernel='poly', max_iter=10000000, C=1)
model_SVC.fit(X, y)
predictions_SVC = model_SVC.predict(X)
print(model_SVC.score(X,y))
print(confusion_matrix(y, predictions_SVC))

0.9138840070298769
[[171  41]
 [  8 349]]


In [11]:
# Análisis de rendimiento del modelo support vector machine - sigmoid SVC
from sklearn import svm

model_SVC = svm.SVC(kernel='sigmoid', max_iter=10000000, C=1)
model_SVC.fit(X, y)
predictions_SVC = model_SVC.predict(X)
print(model_SVC.score(X,y))
print(confusion_matrix(y, predictions_SVC))

0.4446397188049209
[[ 35 177]
 [139 218]]


In [16]:
# Análisis de rendimiento del modelo support vector machine - poly SVC
from sklearn import svm

model_SVC = svm.SVC(kernel='linear', max_iter=10000000, C=100, tol=1e-6)
model_SVC.fit(X, y)
predictions_SVC = model_SVC.predict(X)
print(model_SVC.score(X,y))
print(confusion_matrix(y, predictions_SVC))

0.968365553602812
[[209   3]
 [ 15 342]]
C:\Users\barke\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\svm\_base.py:258: ConvergenceWarning: Solver terminated early (max_iter=10000000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


In [15]:
# Análisis de rendimiento del modelo support vector machine - poly SVC
from sklearn import svm

model_SVC = svm.SVC(kernel='linear', max_iter=10000000, C=10000)
model_SVC.fit(X, y)
predictions_SVC = model_SVC.predict(X)
print(model_SVC.score(X,y))
print(confusion_matrix(y, predictions_SVC))

0.9507908611599297
[[189  23]
 [  5 352]]
C:\Users\barke\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\svm\_base.py:258: ConvergenceWarning: Solver terminated early (max_iter=10000000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
